/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package co.edu.udea.PI.UI;

import co.edu.udea.PI.logica.Logica;
import co.edu.udea.PI.logica.FBF;
import java.awt.Color;

/**
 *
 * @author david
 */
public class PantallaPrincipal extends javax.swing.JFrame {
    
    /**
     * Creates new form Logic
     */
    public PantallaPrincipal() {
        initComponents();
        btnAbrePar.setFocusable(false);
        btnCierraPar.setFocusable(false);
        btnConj.setFocusable(false);
        btnDisy.setFocusable(false);
        btnFlecha.setFocusable(false);
        btnFlechaBi.setFocusable(false);
        btnNegacion.setFocusable(false);
        botonValidar.setFocusable(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        botonValidar = new javax.swing.JButton();
        textExpre1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnNegacion = new javax.swing.JButton();
        btnAbrePar = new javax.swing.JButton();
        btnCierraPar = new javax.swing.JButton();
        btnFlecha = new javax.swing.JButton();
        btnFlechaBi = new javax.swing.JButton();
        btnDisy = new javax.swing.JButton();
        btnConj = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonValidar.setText("Validar");
        botonValidar.setFocusable(false);
        botonValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonValidarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(0));

        btnNegacion.setText("¬");
        btnNegacion.setFocusable(false);
        btnNegacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNegacionActionPerformed(evt);
            }
        });

        btnAbrePar.setText("(");
        btnAbrePar.setFocusable(false);
        btnAbrePar.setMaximumSize(new java.awt.Dimension(22, 27));
        btnAbrePar.setMinimumSize(new java.awt.Dimension(22, 27));
        btnAbrePar.setPreferredSize(new java.awt.Dimension(22, 27));
        btnAbrePar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbreParActionPerformed(evt);
            }
        });

        btnCierraPar.setText(")");
        btnCierraPar.setFocusable(false);
        btnCierraPar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCierraParActionPerformed(evt);
            }
        });

        btnFlecha.setText("→");
        btnFlecha.setFocusable(false);
        btnFlecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlechaActionPerformed(evt);
            }
        });

        btnFlechaBi.setText("↔");
        btnFlechaBi.setFocusable(false);
        btnFlechaBi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlechaBiActionPerformed(evt);
            }
        });

        btnDisy.setText("∨");
        btnDisy.setFocusable(false);
        btnDisy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisyActionPerformed(evt);
            }
        });

        btnConj.setText("∧");
        btnConj.setFocusable(false);
        btnConj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConjActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnNegacion, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAbrePar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCierraPar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFlecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFlechaBi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDisy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConj)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNegacion)
                    .addComponent(btnAbrePar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCierraPar)
                    .addComponent(btnFlecha)
                    .addComponent(btnFlechaBi)
                    .addComponent(btnDisy)
                    .addComponent(btnConj))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Paso", "Proposición a validar", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 75, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textExpre1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(botonValidar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textExpre1)
                        .addGap(2, 2, 2)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonValidar)
                        .addGap(57, 57, 57)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(269, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void botonValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonValidarActionPerformed
        // TODO add your handling code here:
        String expresion = textExpre1.getText();
        
        try {            
            FBF f = new FBF(expresion);  
            textExpre1.setBackground(Color.GREEN);
        } catch (Exception e) {
            textExpre1.setBackground(Color.red);
        }
        
    }//GEN-LAST:event_botonValidarActionPerformed

    private void btnNegacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNegacionActionPerformed

        int pos = textExpre1.getCaretPosition();
        String texto = textExpre1.getText();
        texto = texto.substring(0, pos) + '¬' + texto.substring(pos, texto.length());
        textExpre1.setText(texto);
        textExpre1.setCaretPosition(pos+1);
        
    }//GEN-LAST:event_btnNegacionActionPerformed

    private void btnAbreParActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbreParActionPerformed

        int pos = textExpre1.getCaretPosition();
        String texto = textExpre1.getText();
        texto = texto.substring(0, pos) + '('+ texto.substring(pos, texto.length());
        textExpre1.setText(texto);
        textExpre1.setCaretPosition(pos+1);
       
    }//GEN-LAST:event_btnAbreParActionPerformed

    private void btnCierraParActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCierraParActionPerformed
        
        int pos = textExpre1.getCaretPosition();
        String texto = textExpre1.getText();
        texto = texto.substring(0, pos) + ')'+ texto.substring(pos, texto.length());
        textExpre1.setText(texto);
        textExpre1.setCaretPosition(pos+1);
    }//GEN-LAST:event_btnCierraParActionPerformed

    private void btnFlechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlechaActionPerformed
        
        int pos = textExpre1.getCaretPosition();
        String texto = textExpre1.getText();
        texto = texto.substring(0, pos) + '→'+ texto.substring(pos, texto.length());
        textExpre1.setText(texto);
        textExpre1.setCaretPosition(pos+1);
    }//GEN-LAST:event_btnFlechaActionPerformed

    private void btnFlechaBiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlechaBiActionPerformed
        
        int pos = textExpre1.getCaretPosition();
        String texto = textExpre1.getText();
        texto = texto.substring(0, pos) + '↔'+ texto.substring(pos, texto.length());
        textExpre1.setText(texto);
        textExpre1.setCaretPosition(pos+1);
    }//GEN-LAST:event_btnFlechaBiActionPerformed

    private void btnDisyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisyActionPerformed
        
        int pos = textExpre1.getCaretPosition();
        String texto = textExpre1.getText();
        texto = texto.substring(0, pos) + '∨'+ texto.substring(pos, texto.length());
        textExpre1.setText(texto);
        textExpre1.setCaretPosition(pos+1);
    }//GEN-LAST:event_btnDisyActionPerformed

    private void btnConjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConjActionPerformed
        
        int pos = textExpre1.getCaretPosition();
        String texto = textExpre1.getText();
        texto = texto.substring(0, pos) + '∧'+ texto.substring(pos, texto.length());
        textExpre1.setText(texto);
        textExpre1.setCaretPosition(pos+1);
    }//GEN-LAST:event_btnConjActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonValidar;
    private javax.swing.JButton btnAbrePar;
    private javax.swing.JButton btnCierraPar;
    private javax.swing.JButton btnConj;
    private javax.swing.JButton btnDisy;
    private javax.swing.JButton btnFlecha;
    private javax.swing.JButton btnFlechaBi;
    private javax.swing.JButton btnNegacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField textExpre1;
    // End of variables declaration//GEN-END:variables
}
